version: '2'

services:
  mysql:
    image: mysql:latest
    container_name: phpmyadmin_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    volumes:
      - /sessions
    ports:
      - 8090:80
    environment:
      - PMA_ARBITRARY=1
      - TESTSUITE_PASSWORD=1
    depends_on:
      - mysql