version: '2.1'
services:
  server:
    build: .
    command: npm run dev
    environment:
      - DEBUG_COLORS=true
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - 3000:3000
    links:
      - mongo
    container_name: "RESTserver"
  mongo:
    image: mongo:latest
    command: mongod --smallfiles # --quiet
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./volumes/db:/data/db
    ports:
      - 27017:27017
    container_name: "mongo"